# Generated by Django 3.2.16 on 2023-01-26 07:29

from django.db import migrations, models
import toDoMateProject.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(storage=toDoMateProject.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
