# Generated by Django 3.2.16 on 2023-02-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20230201_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='from_user',
            new_name='block_from_user',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='to_user',
            new_name='block_to_user',
        ),
    ]
